packages:
  - "apps/*"
  - "!apps/backend/.medusa/**"
nodeLinker: hoisted
minimumReleaseAge: 0
overrides:
  emittery: "0.10.0"
allowBuilds:
  '@medusajs/telemetry': false
  '@swc/core': false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
  sharp: false
minimumReleaseAgeExclude:
  - '@posthog/core@1.46.8'
